"""initial schema

Revision ID: 70d0072ec4f2
Revises: 
Create Date: 2026-07-24 21:03:17.903218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '70d0072ec4f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required before any table can use the `vector` column type below
    # (video_ideas.embedding) — see docs/architecture/04-database-design.md.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('niche', sa.String(length=255), nullable=True),
    sa.Column('persona_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_events',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('provider_configs',
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('capability', sa.Enum('LLM', 'TTS', 'IMAGE_GEN', 'VIDEO_GEN', 'STOCK_MEDIA', name='provider_capability'), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_configs_channel_id'), 'provider_configs', ['channel_id'], unique=False)
    op.create_table('video_ideas',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='idea_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_ideas_channel_id'), 'video_ideas', ['channel_id'], unique=False)
    op.create_index('ix_video_ideas_embedding_ivfflat', 'video_ideas', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'})
    op.create_table('projects',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('current_stage', sa.Enum('IDEATION', 'SCRIPTING', 'STORYBOARD', 'VOICEOVER', 'VIDEO_ASSEMBLY', 'THUMBNAIL', 'QA_REVIEW', 'AWAITING_APPROVAL', 'PUBLISHING', 'PUBLISHED', 'FAILED_QA', 'NEEDS_HUMAN_REVIEW', 'REJECTED', name='project_stage'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'FAILED', 'NEEDS_HUMAN_REVIEW', 'COMPLETED', 'CANCELLED', name='project_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['video_ideas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_channel_id'), 'projects', ['channel_id'], unique=False)
    op.create_index(op.f('ix_projects_idea_id'), 'projects', ['idea_id'], unique=False)
    op.create_index('ix_projects_status_stage', 'projects', ['status', 'current_stage'], unique=False)
    op.create_table('assets',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('AUDIO', 'IMAGE', 'VIDEO', 'MUSIC', 'CAPTION', name='asset_type'), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('duration_sec', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_table('jobs',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('queue_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING', name='job_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index('ix_jobs_status_queue', 'jobs', ['status', 'queue_name'], unique=False)
    op.create_table('provider_usage_log',
    sa.Column('provider_config_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_config_id'], ['provider_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_usage_log_project_id'), 'provider_usage_log', ['project_id'], unique=False)
    op.create_index(op.f('ix_provider_usage_log_provider_config_id'), 'provider_usage_log', ['provider_config_id'], unique=False)
    op.create_table('publications',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=True),
    sa.Column('publish_status', sa.Enum('SCHEDULED', 'PUBLISHED', 'FAILED', name='publish_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('privacy_status', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_project_id'), 'publications', ['project_id'], unique=False)
    op.create_table('qa_reports',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_reports_project_id'), 'qa_reports', ['project_id'], unique=False)
    op.create_table('scripts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('target_duration_sec', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SUPERSEDED', name='script_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_project_id'), 'scripts', ['project_id'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('subscribers_gained', sa.Integer(), nullable=False),
    sa.Column('watch_time_minutes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_view_duration_sec', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_performance_metrics_publication_date', 'performance_metrics', ['publication_id', 'metric_date'], unique=False)
    op.create_table('renders',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('duration_sec', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('render_engine', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renders_asset_id'), 'renders', ['asset_id'], unique=False)
    op.create_index(op.f('ix_renders_project_id'), 'renders', ['project_id'], unique=False)
    op.create_table('script_segments',
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('estimated_duration_sec', sa.Integer(), nullable=True),
    sa.Column('scene_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_segments_script_id'), 'script_segments', ['script_id'], unique=False)
    op.create_table('thumbnails',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('variant_label', sa.String(length=50), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnails_asset_id'), 'thumbnails', ['asset_id'], unique=False)
    op.create_index(op.f('ix_thumbnails_project_id'), 'thumbnails', ['project_id'], unique=False)
    op.create_table('storyboard_shots',
    sa.Column('script_segment_id', sa.UUID(), nullable=False),
    sa.Column('shot_type', sa.Enum('STOCK', 'AI_IMAGE', 'AI_VIDEO', 'TEXT_OVERLAY', name='shot_type'), nullable=False),
    sa.Column('prompt_or_query', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['script_segment_id'], ['script_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyboard_shots_asset_id'), 'storyboard_shots', ['asset_id'], unique=False)
    op.create_index(op.f('ix_storyboard_shots_script_segment_id'), 'storyboard_shots', ['script_segment_id'], unique=False)
    op.create_table('voiceovers',
    sa.Column('script_segment_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('duration_sec', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_segment_id'], ['script_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voiceovers_asset_id'), 'voiceovers', ['asset_id'], unique=False)
    op.create_index(op.f('ix_voiceovers_script_segment_id'), 'voiceovers', ['script_segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voiceovers_script_segment_id'), table_name='voiceovers')
    op.drop_index(op.f('ix_voiceovers_asset_id'), table_name='voiceovers')
    op.drop_table('voiceovers')
    op.drop_index(op.f('ix_storyboard_shots_script_segment_id'), table_name='storyboard_shots')
    op.drop_index(op.f('ix_storyboard_shots_asset_id'), table_name='storyboard_shots')
    op.drop_table('storyboard_shots')
    op.drop_index(op.f('ix_thumbnails_project_id'), table_name='thumbnails')
    op.drop_index(op.f('ix_thumbnails_asset_id'), table_name='thumbnails')
    op.drop_table('thumbnails')
    op.drop_index(op.f('ix_script_segments_script_id'), table_name='script_segments')
    op.drop_table('script_segments')
    op.drop_index(op.f('ix_renders_project_id'), table_name='renders')
    op.drop_index(op.f('ix_renders_asset_id'), table_name='renders')
    op.drop_table('renders')
    op.drop_index('ix_performance_metrics_publication_date', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_scripts_project_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_qa_reports_project_id'), table_name='qa_reports')
    op.drop_table('qa_reports')
    op.drop_index(op.f('ix_publications_project_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_provider_usage_log_provider_config_id'), table_name='provider_usage_log')
    op.drop_index(op.f('ix_provider_usage_log_project_id'), table_name='provider_usage_log')
    op.drop_table('provider_usage_log')
    op.drop_index('ix_jobs_status_queue', table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_projects_status_stage', table_name='projects')
    op.drop_index(op.f('ix_projects_idea_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_channel_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_video_ideas_embedding_ivfflat', table_name='video_ideas', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'})
    op.drop_index(op.f('ix_video_ideas_channel_id'), table_name='video_ideas')
    op.drop_table('video_ideas')
    op.drop_index(op.f('ix_provider_configs_channel_id'), table_name='provider_configs')
    op.drop_table('provider_configs')
    op.drop_table('users')
    op.drop_table('system_events')
    op.drop_table('channels')
    # ### end Alembic commands ###
